spring:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./db
    username: admin
    password:

server:
  port: 8080

logging:
  level:
    org.springframework: DEBUG
    org.simplejavamail: TRACE

simplejavamail:
  javaxmail:
    debug: true